### ISSUE TITLE
Colab example fails

### ISSUE THREAD

**Issue by smistad** [magnusdk/vbeam#13]
I tried the colab example at https://colab.research.google.com/github/magnusdk/vbeam/blob/main/docs/examples/plane_wave_dataset.ipynb#scrollTo=ltsYNeBEIPTn

Using jax for CPU this results in the following error:
```
Traceback (most recent call last):
  File "/home/smistad/workspace/vbeam-test/test.py", line 13, in <module>
    setup = import_pyuff(channel_data, scan, frames=0)
  File "/home/smistad/workspace/vbeam-test/venv/lib/python3.9/site-packages/vbeam/data_importers/pyuff_importer.py", line 103, in import_pyuff
    np.array(channel_data.probe.xyz),
  File "/home/smistad/workspace/vbeam-test/venv/lib/python3.9/site-packages/pyuff_ustb/objects/probes/probe.py", line 83, in xyz
    return np.stack([self.x, self.y, self.z], -1)
  File "/home/smistad/workspace/vbeam-test/venv/lib/python3.9/site-packages/pyuff_ustb/objects/probes/probe.py", line 68, in x
    return self.geometry[0]
  File "/home/smistad/workspace/vbeam-test/venv/lib/python3.9/site-packages/pyuff_ustb/objects/probes/linear_array.py", line 72, in geometry
    np.zeros(self.N),
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by magnusdk** [comment]
Hi! This should be fixed now. It was a bug in [`pyuff_ustb`](https://github.com/magnusdk/pyuff_ustb).

BTW, I was able to see that vbeam uses a ton of memory when running on the CPU. [I created an issue here](https://github.com/magnusdk/vbeam/issues/14), and will look into why that is.

Closing this issue as fixed.
